//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/Calc.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CalcParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface ICalcVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartrule([NotNull] CalcParser.StartruleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryAddInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryAddInt([NotNull] CalcParser.BinaryAddIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryAddSimple</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryAddSimple([NotNull] CalcParser.BinaryAddSimpleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryMultiplyInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryMultiplyInt([NotNull] CalcParser.BinaryMultiplyIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinarySubstractInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinarySubstractInt([NotNull] CalcParser.BinarySubstractIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryDivisionInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryDivisionInt([NotNull] CalcParser.BinaryDivisionIntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryModulusInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryModulusInt([NotNull] CalcParser.BinaryModulusIntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.signedatom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignedatom([NotNull] CalcParser.SignedatomContext context);
}
