//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/Calc.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CalcParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface ICalcListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryAddInt</c>
	/// labeled alternative in <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryAddInt([NotNull] CalcParser.BinaryAddIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryAddInt</c>
	/// labeled alternative in <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryAddInt([NotNull] CalcParser.BinaryAddIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryMultiplyInt</c>
	/// labeled alternative in <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryMultiplyInt([NotNull] CalcParser.BinaryMultiplyIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryMultiplyInt</c>
	/// labeled alternative in <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryMultiplyInt([NotNull] CalcParser.BinaryMultiplyIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BinarySubstractInt</c>
	/// labeled alternative in <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinarySubstractInt([NotNull] CalcParser.BinarySubstractIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BinarySubstractInt</c>
	/// labeled alternative in <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinarySubstractInt([NotNull] CalcParser.BinarySubstractIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryDivisionInt</c>
	/// labeled alternative in <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryDivisionInt([NotNull] CalcParser.BinaryDivisionIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryDivisionInt</c>
	/// labeled alternative in <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryDivisionInt([NotNull] CalcParser.BinaryDivisionIntContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryModulusInt</c>
	/// labeled alternative in <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryModulusInt([NotNull] CalcParser.BinaryModulusIntContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryModulusInt</c>
	/// labeled alternative in <see cref="CalcParser.startrule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryModulusInt([NotNull] CalcParser.BinaryModulusIntContext context);
}
