//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/Calc.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CalcParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface ICalcListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartRule([NotNull] CalcParser.StartRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartRule([NotNull] CalcParser.StartRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CalcParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CalcParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.addition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddition([NotNull] CalcParser.AdditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.addition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddition([NotNull] CalcParser.AdditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.multiplication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplication([NotNull] CalcParser.MultiplicationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.multiplication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplication([NotNull] CalcParser.MultiplicationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] CalcParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] CalcParser.AtomContext context);
}
