//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/Calc.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public partial class CalcParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		PLUS=1, TIMES=2, MINUS=3, DIVISION=4, MODULUS=5, INT=6;
	public const int
		RULE_startrule = 0;
	public static readonly string[] ruleNames = {
		"startrule"
	};

	private static readonly string[] _LiteralNames = {
		null, "'+'", "'*'", "'-'", "'/'", "'%'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "PLUS", "TIMES", "MINUS", "DIVISION", "MODULUS", "INT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Calc.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CalcParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public CalcParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public CalcParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StartruleContext : ParserRuleContext {
		public StartruleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_startrule; } }
	 
		public StartruleContext() { }
		public virtual void CopyFrom(StartruleContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class BinaryMultiplyIntContext : StartruleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INT() { return GetTokens(CalcParser.INT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT(int i) {
			return GetToken(CalcParser.INT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TIMES() { return GetToken(CalcParser.TIMES, 0); }
		public BinaryMultiplyIntContext(StartruleContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterBinaryMultiplyInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitBinaryMultiplyInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryMultiplyInt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinaryAddIntContext : StartruleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INT() { return GetTokens(CalcParser.INT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT(int i) {
			return GetToken(CalcParser.INT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(CalcParser.PLUS, 0); }
		public BinaryAddIntContext(StartruleContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterBinaryAddInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitBinaryAddInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryAddInt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinaryModulusIntContext : StartruleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INT() { return GetTokens(CalcParser.INT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT(int i) {
			return GetToken(CalcParser.INT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MODULUS() { return GetToken(CalcParser.MODULUS, 0); }
		public BinaryModulusIntContext(StartruleContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterBinaryModulusInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitBinaryModulusInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryModulusInt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinarySubstractIntContext : StartruleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INT() { return GetTokens(CalcParser.INT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT(int i) {
			return GetToken(CalcParser.INT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(CalcParser.MINUS, 0); }
		public BinarySubstractIntContext(StartruleContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterBinarySubstractInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitBinarySubstractInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinarySubstractInt(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinaryDivisionIntContext : StartruleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INT() { return GetTokens(CalcParser.INT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT(int i) {
			return GetToken(CalcParser.INT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIVISION() { return GetToken(CalcParser.DIVISION, 0); }
		public BinaryDivisionIntContext(StartruleContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.EnterBinaryDivisionInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICalcListener typedListener = listener as ICalcListener;
			if (typedListener != null) typedListener.ExitBinaryDivisionInt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcVisitor<TResult> typedVisitor = visitor as ICalcVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryDivisionInt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StartruleContext startrule() {
		StartruleContext _localctx = new StartruleContext(Context, State);
		EnterRule(_localctx, 0, RULE_startrule);
		try {
			State = 17;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				_localctx = new BinaryAddIntContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 2; Match(INT);
				State = 3; Match(PLUS);
				State = 4; Match(INT);
				}
				break;
			case 2:
				_localctx = new BinaryMultiplyIntContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 5; Match(INT);
				State = 6; Match(TIMES);
				State = 7; Match(INT);
				}
				break;
			case 3:
				_localctx = new BinarySubstractIntContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 8; Match(INT);
				State = 9; Match(MINUS);
				State = 10; Match(INT);
				}
				break;
			case 4:
				_localctx = new BinaryDivisionIntContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 11; Match(INT);
				State = 12; Match(DIVISION);
				State = 13; Match(INT);
				}
				break;
			case 5:
				_localctx = new BinaryModulusIntContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 14; Match(INT);
				State = 15; Match(MODULUS);
				State = 16; Match(INT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\b', '\x16', '\x4', '\x2', '\t', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', '\x2', 
		'\x14', '\n', '\x2', '\x3', '\x2', '\x2', '\x2', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x18', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x4', 
		'\x5', '\a', '\b', '\x2', '\x2', '\x5', '\x6', '\a', '\x3', '\x2', '\x2', 
		'\x6', '\x14', '\a', '\b', '\x2', '\x2', '\a', '\b', '\a', '\b', '\x2', 
		'\x2', '\b', '\t', '\a', '\x4', '\x2', '\x2', '\t', '\x14', '\a', '\b', 
		'\x2', '\x2', '\n', '\v', '\a', '\b', '\x2', '\x2', '\v', '\f', '\a', 
		'\x5', '\x2', '\x2', '\f', '\x14', '\a', '\b', '\x2', '\x2', '\r', '\xE', 
		'\a', '\b', '\x2', '\x2', '\xE', '\xF', '\a', '\x6', '\x2', '\x2', '\xF', 
		'\x14', '\a', '\b', '\x2', '\x2', '\x10', '\x11', '\a', '\b', '\x2', '\x2', 
		'\x11', '\x12', '\a', '\a', '\x2', '\x2', '\x12', '\x14', '\a', '\b', 
		'\x2', '\x2', '\x13', '\x4', '\x3', '\x2', '\x2', '\x2', '\x13', '\a', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '\n', '\x3', '\x2', '\x2', '\x2', 
		'\x13', '\r', '\x3', '\x2', '\x2', '\x2', '\x13', '\x10', '\x3', '\x2', 
		'\x2', '\x2', '\x14', '\x3', '\x3', '\x2', '\x2', '\x2', '\x3', '\x13',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
