//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/Calc.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICalcListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CalcBaseListener : ICalcListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.startrule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStartrule([NotNull] CalcParser.StartruleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.startrule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStartrule([NotNull] CalcParser.StartruleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryAddInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryAddInt([NotNull] CalcParser.BinaryAddIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryAddInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryAddInt([NotNull] CalcParser.BinaryAddIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryAddSimple</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryAddSimple([NotNull] CalcParser.BinaryAddSimpleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryAddSimple</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryAddSimple([NotNull] CalcParser.BinaryAddSimpleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryMultiplyInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryMultiplyInt([NotNull] CalcParser.BinaryMultiplyIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryMultiplyInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryMultiplyInt([NotNull] CalcParser.BinaryMultiplyIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinarySubstractInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinarySubstractInt([NotNull] CalcParser.BinarySubstractIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinarySubstractInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinarySubstractInt([NotNull] CalcParser.BinarySubstractIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryDivisionInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryDivisionInt([NotNull] CalcParser.BinaryDivisionIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryDivisionInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryDivisionInt([NotNull] CalcParser.BinaryDivisionIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryModulusInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryModulusInt([NotNull] CalcParser.BinaryModulusIntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryModulusInt</c>
	/// labeled alternative in <see cref="CalcParser.binaryexpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryModulusInt([NotNull] CalcParser.BinaryModulusIntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.signedatom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSignedatom([NotNull] CalcParser.SignedatomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.signedatom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSignedatom([NotNull] CalcParser.SignedatomContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
